export const nodes = [
    { id: "0", name: "Foundations" },
    { id: "1", name: "Basic ROS2" },
    { id: "2", name: "ROS Basics" },
    { id: "3", name: "Advanced Modern C++ for robotics" },
    { id: "4", name: "Robotics Theory" },
    { id: "5", name: "Navigation ROS2" },
    { id: "6", name: "Manipulation" },
    { id: "7", name: "Robot Creation" },
    { id: "8", name: "Gazebo Sim with ROS2" },
    { id: "9", name: "Artificial Intelligence" },
    { id: "10", name: "ROS Debugging" },
    { id: "11", name: "Enterprise" },
    { id: "12", name: "Course of product" },
    { id: "13", name: "Simulation" },
    { id: "14", name: "Intermediate ROS2 (Python)" },
    { id: "15", name: "Intermediate ROS2 (C++)" },
    { id: "16", name: "Behavior Trees for ROS2" },
    { id: "17", name: "ROS2 Control" },
    { id: "18", name: "Autonomous Systems" },
    { id: "19", name: "Safety-Critical Systems" },
    { id: "20", name: "Ethics in Robotics" },
];

  
  export const links = [
    { source: "0", target: "1" },
    { source: "1", target: "2" },
    { source: "1", target: "3" },
    { source: "1", target: "4" },
    { source: "1", target: "5" },
    { source: "2", target: "6" },
    { source: "2", target: "7" },
    { source: "2", target: "8" },
    { source: "3", target: "9" },
    { source: "4", target: "10" },
    { source: "5", target: "11" },
    { source: "7", target: "12" },
    { source: "8", target: "13" },
    { source: "9", target: "14" },
    { source: "9", target: "15" },
    { source: "10", target: "16" },
    { source: "11", target: "17" },
  ];